import os
import Dist

#==============================================================================
# Write KCore installation path to installPath.py
Dist.writeInstallPath()

prod = os.getenv("ELSAPROD")
if prod is None:
  variant_dir="build"
else:
  variant_dir=os.path.join('build/',prod)

SConscript('setup.scons', variant_dir=variant_dir)
